version: 2
jobs:
  build:
    working_directory: ~/likecoin-tunnel
    docker:
      - image: node:10
      - image: ethereum/client-go:stable
        command: ['--rpc', '--rpcaddr', '0.0.0.0', '--rpcapi', 'eth,web3', '--syncmode', 'light']
    steps:
      - checkout
      - restore_cache:
          key: likecoin-tunnel-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm install
      - run:
          name: Lint Test
          command: npm run lint
      - run:
          name: Server Test
          command: npm start
          background: true
      - run:
          name: wget Test
          command: |
            sleep 5
            wget -O- --retry-connrefused --waitretry=5 -t 10 http://127.0.0.1:3000/ > /dev/null
      - save_cache:
          key: likecoin-tunnel-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
